version: "0.0.1 #{build}"

image:
- Visual Studio 2017
- Ubuntu

init:
  - git config --global core.autocrlf input

install:
  - dotnet --version
  - dotnet restore Gog-WebApiKit.sln

build_script:
  - dotnet build Gog-WebApiKit.sln

test: off
