version: "0.0.1 #{build}"

platform:
  - x64

image:
- Visual Studio 2017
- Ubuntu

init:
  - git config --global core.autocrlf input

install:
  - dotnet restore

build_script:
  - dotnet build

test: off
